whp_core/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^dashboard', dashboard, name='dashboard'),
    url(r'^forum', forum, name='forum'),
    url(r'^quiz', quiz, name='quiz'),
    url(r'^text', text, name='text'),
    url(r'^video', video, name='video'),
    url(r'^profile', profile, name='profile'),
]

woowhoproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import whp_core.urls as core

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(core,namespace='core'))
]

whp_core/models.py
from django.db import models

# Create your models here.

whp_core/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def index(request):
    html = "home.html"
    return render(request, html)

@csrf_exempt
def dashboard(request):
    html = "dashboard.html"
    return render(request, html)

@csrf_exempt
def forum(request):
    html = "forum.html"
    return render(request, html)

@csrf_exempt
def quiz(request):
    html = "quiz.html"
    return render(request, html)

@csrf_exempt
def text(request):
    html = "text.html"
    return render(request, html)

@csrf_exempt
def video(request):
    html = "video.html"
    return render(request, html)

@csrf_exempt
def profile(request):
    html = "profile.html"
    return render(request, html)

whp_core/templates/dashboard.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- PAGE settings -->
    <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
    <title>The Woo-Who Project</title>
    <meta name="description" content="The Woo-Who Project : A project made by The Ponderings. Submitted as a final assignment for PBK course.">
    <!-- CSS dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css">
    <link rel="stylesheet" href="{% static 'css/colorful.css' %}" type="text/css" %>
    <!-- Script: Navbar on-top -->
    <script src="{% static 'js/navbar-ontop.js' %}"></script>
    <!--<script src="js/navbar-ontop.js"></script>-->
</head>

<body>
<nav class="navbar navbar-expand-md fixed-top navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand" href="/">
            <b class="text-primary">Woo-Who Project</b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbar3SupportedContent" aria-controls="navbar3SupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar3SupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item mx-2 mb-2 my-md-0">
                    <a class="nav-link" href="{% url 'core:forum' %}">Forum</a>
                </li>
                <li class="nav-item mx-2 mb-2 my-md-0">
                    <a class="btn btn-outline-primary" href="{% url 'core:profile' %}">Profile</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="py-5 text-center cover d-flex flex-column bg-light">
    <div class="container my-auto">
        <div class="row">
            <div class="mx-auto col-lg-6 col-md-12 col-xl-12"></div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-white text-dark" style="border-radius: 8px 8px 0px 0px"> Your End Goal
                    </div>
                    <div class="card-body">
                        <p>Expressing myself without fearing criticism.</p>
                        <a href="#" class="btn btn-outline-primary">Edit Goal</a>
                    </div>
                </div>
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-white text-dark" style="border-radius: 8px 8px 0px 0px">Your Coach</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <img class="card-img rounded-circle" src="static/assets/team/yellow.jpg"
                                     alt="Card image">
                            </div>
                            <div class="col-md-6 px-1">
                                <p>Brandon</p>
                                <a href="#" class="btn btn-outline-primary">Contact</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-primary text-white text-left" style="border-radius: 8px 8px 0px 0px">
                        Next Activity
                    </div>
                    <div class="card-body">
                        <h6 class="text-muted text-left">Week 1</h6>
                        <h4 class="text-left">Measuring Progress</h4>
                        <p class="text-left">In this activity, we will build on your self-confidence in crowds!</p>
                        <a href="{% url 'core:text' %}" class="btn btn-outline-primary">Start your Activity</a>
                    </div>
                </div>
                <div class="card my-3" style="border-radius: 8px;">
                    <div class="card-header bg-white text-dark text-left" style="border-radius: 8px 8px 0px 0px">
                        Overview
                    </div>
                    <div class="card-body">
                        <ul class="nav nav-tabs">
                            <li class="nav-item" style="border-radius:8px;">
                                <a href="" class="active nav-link" data-toggle="tab" data-target="#tabone">Week 1</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="" data-toggle="tab" data-target="#tabtwo">Week 2</a>
                            </li>
                            <li class="nav-item">
                                <a href="" class="nav-link" data-toggle="tab" data-target="#tabthree">Week 3</a>
                            </li>
                        </ul>
                        <div class="tab-content mt-2">
                            <div class="tab-pane fade show active" id="tabone" role="tabpanel">
                                <h4 class="text-left py-2">
                                    <strong>Learn More About Social Anxiety</strong>
                                </h4>
                                <p class="text-left">
                                    <span class="fa fa-unlock fa-fw"></span>Measuring Progress</p>
                                <p class="text-left text-muted">
                                    <span class="fa fa-lock fa-fw"></span>Measuring Progress</p>
                                <p class="text-left text-muted">
                                    <span class="fa fa-lock fa-fw"></span>What is Social Anxiety</p>
                                <p class="text-left text-muted">
                                    <span class="fa fa-lock fa-fw"></span>A Quick Tool</p>
                                <p class="text-left text-muted">
                                    <span class="fa fa-lock fa-fw"></span>The 3 Parts of Social Anxiety</p>
                                <p class="text-left text-muted">
                                    <span class="fa fa-lock fa-fw"></span>Spiral of Social Anxiety</p>
                            </div>
                            <div class="tab-pane fade" id="tabtwo" role="tabpanel">
                                <p class="">Tab pane two. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                            <div class="tab-pane fade" id="tabthree" role="tabpanel">
                                <p class="">Tab pane three. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card my-3">
                    <div class="card-header bg-white text-left"> Challenges</div>
                    <div class="card-body">
                        <h4 class="text-left">
                            <strong>Weekly Challenges</strong>
                        </h4>
                        <p class="text-left">1. Lorem ipsum dolor sit amet</p>
                        <p class="text-left">2. Lorem ipsum dolor sit amet</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="text-white" id="where">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-3">
                <p class="text-center text-muted">© Copyright 2018 The Woo-Who Project - All rights reserved. </p>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<!-- Script: Smooth scrolling between anchors in the same page -->
<script src="js/smooth-scroll.js"></script>
</body>

</html>

whp_core/templates/forum.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- PAGE settings -->
    <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
    <title>The Woo-Who Project</title>
    <meta name="description" content="The Woo-Who Project : A project made by The Ponderings. Submitted as a final assignment for PBK course.">
    <!-- CSS dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css">
    <link rel="stylesheet" href="{% static 'css/colorful.css' %}" type="text/css" %>
    <!-- Script: Navbar on-top -->
    <script src="{% static 'js/navbar-ontop.js' %}"></script>
    <!--<script src="js/navbar-ontop.js"></script>-->
</head>

<body>
<nav class="navbar navbar-expand-md fixed-top navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand" href="/">
            <b class="text-primary">Woo-Who Project</b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbar3SupportedContent" aria-controls="navbar3SupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar3SupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item mx-2 mb-2 my-md-0">
                    <a class="nav-link" href="{% url 'core:forum' %}">Forum</a>
                </li>
                <li class="nav-item mx-2 mb-2 my-md-0">
                    <a class="btn btn-outline-primary" href="{% url 'core:profile' %}">Profile</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="py-5 text-center cover d-flex flex-column bg-light">
    <div class="container my-auto">
        <div class="row">
            <div class="mx-auto col-lg-6 col-md-12 col-xl-12"></div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-white text-dark" style="border-radius: 8px 8px 0px 0px"> Your End Goal
                    </div>
                    <div class="card-body">
                        <p>Expressing myself without fearing criticism.</p>
                        <a href="#" class="btn btn-outline-primary">Edit Goal</a>
                    </div>
                </div>
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-white text-dark" style="border-radius: 8px 8px 0px 0px">Your Coach</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <img class="card-img rounded-circle" src="static/assets/team/yellow.jpg"
                                     alt="Card image">
                            </div>
                            <div class="col-md-6 px-1">
                                <p>Brandon</p>
                                <a href="#" class="btn btn-outline-primary">Contact</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-primary text-white text-left" style="border-radius: 8px 8px 0px 0px">
                        Weekly Discussion Topic
                    </div>
                    <div class="card-body">
                        <h4 class="text-left">Weekly Discussion Topic Here</h4>
                        <p class="text-left">Weekly discussion topic description.</p>
                    </div>
                </div>
                <div class="card my-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-1">
                                <img class="card-img rounded-circle px-0" src="static/assets/team/yellow.jpg"
                                     alt="Card image">
                            </div>
                            <div class="col-md-10">
                                <p class="lead text-left">Lead paragraph </p>
                                <p class="card-text text-left">By Jesse - Friday, May 25 2018, 8:52 PM</p>
                                <p class="card-text text-left">Some quick example text to build on the card title and make up the
                                    bulk of the card's content.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card my-3">
                    <div class="card-body">
                        <h5 class="card-title">Reply</h5>
                        <form class="">
                            <div class="form-group">
                                <textarea type="email" class="form-control" placeholder="Enter email"
                                          style="margin-top: 0px; margin-bottom: 0px; height: 163px;"></textarea>
                            </div>
                            <button type="submit" class="btn btn-outline-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="text-white" id="where">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-3">
                <p class="text-center text-muted">© Copyright 2018 The Woo-Who Project - All rights reserved. </p>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<!-- Script: Smooth scrolling between anchors in the same page -->
<script src="js/smooth-scroll.js"></script>
</body>

</html>

whp_core/templates/profile.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- PAGE settings -->
    <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
    <title>The Woo-Who Project</title>
    <meta name="description" content="The Woo-Who Project : A project made by The Ponderings. Submitted as a final assignment for PBK course.">
    <!-- CSS dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css">
    <link rel="stylesheet" href="{% static 'css/colorful.css' %}" type="text/css" %>
    <!-- Script: Navbar on-top -->
    <script src="{% static 'js/navbar-ontop.js' %}"></script>
    <!--<script src="js/navbar-ontop.js"></script>-->
</head>

<body>
<nav class="navbar navbar-expand-md fixed-top navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand" href="#">
            <b class="text-primary">Woo-Who Project</b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbar3SupportedContent" aria-controls="navbar3SupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar3SupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item mx-2 mb-2 my-md-0">
                    <a class="nav-link" href="{% url 'core:forum' %}">Forum</a>
                </li>
                <li class="nav-item mx-2 mb-2 my-md-0">
                    <a class="btn btn-outline-primary" href="{% url 'core:profile' %}">Profile</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="py-5 text-center cover d-flex flex-column bg-light">
    <div class="container my-auto">
        <div class="row">
            <div class="mx-auto col-lg-6 col-md-12 col-xl-12"></div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-white text-dark" style="border-radius: 8px 8px 0px 0px"> Profile
                        Picture
                    </div>
                    <div class="card-body">
                        <img class="card-img rounded-circle" src="static/assets/team/blue.jpg" alt="Card image">
                        <a href="#" class="btn btn-outline-primary my-3">Edit Profile Picture</a>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-primary text-white text-left" style="border-radius: 8px 8px 0px 0px">
                        Basics
                    </div>
                    <div class="card-body">
                        <form class="">
                            <div class="form-group">
                                <label class="text-left">First Name</label>
                                <input type="text" class="form-control" placeholder="First Name"></div>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" placeholder="Last Name"></div>
                            <div class="form-group">
                                <label>Date of Birth</label>
                                <input type="date" class="form-control"></div>
                            <div class="form-group">
                                <label>Gender</label>
                                <select class="form-control">
                                    <option>Male</option>
                                    <option>Female</option>
                                    <option>Prefer not to say</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-outline-primary">Save</button>
                        </form>
                    </div>
                </div>
                <div class="card my-3">
                    <div class="card-header bg-white text-left" style="
	border-radius: 8px 8px 0px 0px"> Challenge Rewards
                    </div>
                    <div class="card-body">
                        <h4 class="text-left">
                            <strong>Rewards Tally</strong>
                        </h4>
                        <div class="row">
                            <div class="col-md-3">
                                <img src="https://png.icons8.com/color/100/000000/medal.png"></div>
                            <div class="col-md-9">
                                <h2 class="text-left d-flex justify-content-start">5 medals.</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="text-white" id="where">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mt-3">
                <p class="text-center text-muted">© Copyright 2018 The Woo-Who Project - All rights reserved. </p>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<!-- Script: Smooth scrolling between anchors in the same page -->
<script src="js/smooth-scroll.js"></script>
</body>

</html>

whp_core/templates/quiz.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- PAGE settings -->
    <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
    <title>The Woo-Who Project</title>
    <meta name="description" content="The Woo-Who Project : A project made by The Ponderings. Submitted as a final assignment for PBK course.">
    <!-- CSS dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css">
    <link rel="stylesheet" href="{% static 'css/colorful.css' %}" type="text/css" %>
    <!-- Script: Navbar on-top -->
    <script src="{% static 'js/navbar-ontop.js' %}"></script>
    <!--<script src="js/navbar-ontop.js"></script>-->
</head>

<body>
<div class="py-5 text-center cover d-flex flex-column bg-light">
    <div class="container my-auto">
        <div class="row">
            <div class="mx-auto col-lg-6 col-md-12 col-xl-12"></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card my-3" style="border-radius: 8px;">
                    <div class="card-header bg-primary text-white" style="border-radius: 8px 8px 0px 0px"> Getting To
                        Know You
                    </div>
                    <div class="card-body px-4">
                        <h4>How much has persistent anxiety or stress intefered with your ability to work?</h4>
                        <form id="form" method="POST" action="{% url 'core:dashboard' %}">
                            <div class="radio">
                                <label class="container2 text-left" draggable="true">Not at all
                                    <input type="radio" checked="checked" name="radio" value="on">
                                    <span class="checkmark"></span>
                                </label>
                                <label class="container2 text-left">Somewhat
                                    <input type="radio" checked="checked" name="radio" value="on">
                                    <span class="checkmark"></span>
                                </label>
                                <label class="container2 text-left">Very much
                                    <input type="radio" checked="checked" name="radio" value="on">
                                    <span class="checkmark"></span>
                                </label>
                                <label class="container2 text-left">Extremely
                                    <input type="radio" checked="checked" name="radio" value="on">
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                            <button type="submit" class="btn btn-outline-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-md fixed-top navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand" href="#">
            <b class="text-primary">Woo-Who Project</b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbar3SupportedContent" aria-controls="navbar3SupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar3SupportedContent"></div>
    </div>
</nav>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<!-- Script: Smooth scrolling between anchors in the same page -->
<script src="js/smooth-scroll.js"></script>
</body>

</html>

whp_core/templates/text.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- PAGE settings -->
    <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
    <title>The Woo-Who Project</title>
    <meta name="description" content="The Woo-Who Project : A project made by The Ponderings. Submitted as a final assignment for PBK course.">
    <!-- CSS dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css">
    <link rel="stylesheet" href="{% static 'css/colorful.css' %}" type="text/css" %>
    <!-- Script: Navbar on-top -->
    <script src="{% static 'js/navbar-ontop.js' %}"></script>
    <!--<script src="js/navbar-ontop.js"></script>-->
</head>

<body>
<nav class="navbar navbar-expand-md fixed-top navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand" href="/">
            <b class="text-primary">Woo-Who Project</b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbar3SupportedContent" aria-controls="navbar3SupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar3SupportedContent"></div>
    </div>
</nav>
<div class="py-5 text-center cover d-flex flex-column bg-light">
    <div class="container my-auto">
        <div class="row">
            <div class="mx-auto col-lg-6 col-md-12 col-xl-12"></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card my-3" style="border-radius: 8px">
                    <div class="card-header bg-primary text-white" style="border-radius: 8px 8px 0px 0px"> Getting to
                        Know Social Anxiety
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <img src="https://png.icons8.com/color/200/000000/object.png">
                            </div>
                            <div class="col-md-6 ">
                                <h4 class="text text-left"> Everyone experiences some level of social anxiety.</h4>
                                <p class="text text-left">Imagining what others think is the foundation of empathy, and
                                    helps us connect with others. This becomes a problem—clinical social anxiety—when
                                    the focus on what others think begins to interfere with your ability to lead the
                                    life you
                                    want.</p>
                            </div>
                        </div>
                        <a href="{% url 'core:video' %}" class="btn btn-outline-primary m-2">Next</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<!-- Script: Smooth scrolling between anchors in the same page -->
<script src="js/smooth-scroll.js"></script>
</body>

</html>